---
title: "KFL 2023 Draft Order"
author: "Sam Kirschner"
date: 2023-08-14T13:09:13-06:00
output: html_document
---


## KFL 2023 Draft Standings

A reminder to how the order is determined the rules are as follows

1) Your record determines your draft order unless you made the playoffs. The 4 playoff teams have their draft order determined by playoff performance
2) In the case of a tie record for non-playoff teams, your performance in the consolation round determines seeding. So if two teams tie in record, the team that wins their consolation round game(s) will get the higher draft position. 
  - If the teams with a tie record both win their first round consolation game, it moves on to the second round. If teams with tie records win both conosolation games then the tiebreaker is points for. 


2022 KFL DRAFT ORDER
1) Michael's GMOS (3-11)
2) Diamond Dogs (5-9; Round 2 Tiebreaker Winner)
3) Kurt's The Tenderloins (5-9; Round 2 Tiebreaker Loser)
4) Elliot's Last Good Tight End (5-9; Round 1 Tiebreaker Loser)
5) Cincinnati MountainMen (6-8)
6) Scott's Titans (7-7; Round 1 Tiebreaker Winner)
7) Joe S Sunday Winners (7-7; Round 1 Tiebreaker Loser)
8) Jeff's Slugs (8-6)
9) Sam's Bluecats (4th Place)
10) Nick's Unlucky Ducks (3rd Place Winner)
11) Alex's Kraken (2nd Place Winner)
12) Ruwe's Onionheads (1st Place Winner)
